# Generated by Django 4.2.5 on 2023-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
