# Generated by Django 4.2.5 on 2023-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('robots', '0004_remove_robot_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='orders',
            field=models.ManyToManyField(blank=True, to='orders.order'),
        ),
    ]
